#!/usr/bin/env ruby

commit_messages = File.readlines(ARGV[0]).join('')
open(ARGV[0], 'w') do |file|
  branch_raw = `git rev-parse --abbrev-ref HEAD`
  branch = branch_raw.match(/(LLWEBCONT|HAY)-(\d+)/)
  prefix = "#{branch[1]}-#{branch[2]}: " if branch
  prefix = "#{branch}: " if branch
  file.print prefix if prefix && !commit_messages.start_with?(prefix)
  file.puts commit_messages
end

